### PR TITLE
Fix deprecated hardwareInterface name for Kinetic

### PR DESCRIPTION
**Pull request by davetcoleman**
This PR needs to be targeted to a kinetic branch

Fix for https://github.com/ros-simulation/gazebo_ros_pkgs/pull/550

### CODE REVIEW

**Comment by IanTheEngineer** [comment]
kk, I'll create a `kinetic-devel`

**Comment by IanTheEngineer** [comment]
Same deal as #87 with the master-merge commits. Can you please manually rebase onto `kinetic-devel` to remove those unnecessary commits? Thanks!

**Review by IanTheEngineer — APPROVED** [review]
Looks good to merge after a rebase onto `kinetic-devel`

**Comment by davetcoleman** [comment]
I have rebased

**Comment by IanTheEngineer** [comment]
Thanks for the rebase!

**Pull request merged**
