### PR TITLE
[baxter_description] add electric gripper if condition in baxter.urdf.xacro

### PR DESCRIPTION
**Pull request by knorth55**
add if condition, otherwise every time electric grippers are loaded to gazebo.

### CODE REVIEW

**Comment by knorth55** [comment]
ping

**Comment by davetcoleman** [comment]
+1

**Comment by knorth55** [comment]
@IanTheEngineer can you review this, too?

**Comment by IanTheEngineer** [comment]
@knorth55, apologies for the delay in review. I have just added https://github.com/RethinkRobotics/baxter_common/pull/90 which accounts for "null grippers" which must still include the `<side>_gripper` endpoint. Does this meet the needs from your PR?

**Pull request closed without merging**
