### PR TITLE
[baxter_description] Add argument of 'end_effectors' in 'baxter.urdf.xacro

### PR DESCRIPTION
**Pull request by wkentaro**
to include this file and customize the end-effector with another urdf model.

### CODE REVIEW

**Comment by k-okada** [comment]
or you can update https://github.com/RethinkRobotics/baxter_common/tree/arg_grippers_xacro branch if that is under development @rethink-imcmahon

**Comment by davetcoleman** [comment]
+1

**Comment by davetcoleman** [comment]
Actually, I think https://github.com/RethinkRobotics/baxter_common/pull/79 replaces this PR

**Comment by IanTheEngineer** [comment]
Sorry for the delay all. Does #90 meet the desires of this PR? You can supply `right_electric_gripper:=false` to suppress an endpoint, while keeping a full and valid Baxter URDF, with a `right_gripper` endpoint.

**Comment by wkentaro** [comment]
Yes, #90 is fine, and I can close this PR.

**Pull request closed without merging**
